- name: Deploy to EC2
  run: |
    ssh -i ~/.ssh/ec2_key.pem ec2-user@ec2-54-81-72-20.compute-1.amazonaws.com << 'EOF'
      # Navigate to the home directory
      cd ~
      
      # Clone the repository if it does not exist
      if [ ! -d "my-node-app" ]; then
        git clone https://github.com/YOUR-USERNAME/YOUR-REPO.git my-node-app
      fi

      # Navigate to the app directory
      cd my-node-app

      # Ensure we're on the correct branch
      git checkout main
      git reset --hard origin/main
      git pull origin main

      # Install dependencies
      npm install

      # Kill any existing process
      pkill -f "node agent.js" || echo "No existing process found"

      # Restart the app in the background
      nohup node agent.js > app.log 2>&1 &

      # Verify process is running
      sleep 2
      ps aux | grep node
    EOF
