name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/ec2_key.pem
        chmod 600 ~/.ssh/ec2_key.pem
        ssh-keyscan -H ec2-35-175-186-138.compute-1.amazonaws.com >> ~/.ssh/known_hosts

    - name: Deploy to EC2
      run: |
        ssh -i ~/.ssh/ec2_key.pem ec2-user@ec2-35-175-186-138.compute-1.amazonaws.com << 'EOF'
          set -e  # Exit on error

          # Navigate to home directory
          cd ~

          # Check if repository exists
          if [ ! -d "my-node-app" ]; then
            echo "Cloning repository..."
            git clone https://github.com/git-union/SmartPortfolio.git my-node-app
          fi

          # Navigate to app directory
          cd my-node-app

          # Ensure latest code is pulled
          echo "Fetching latest code..."
          git reset --hard origin/main
          git pull origin main

          # Install dependencies
          echo "Installing dependencies..."
          npm install

          # Stop the running app (if any)
          echo "Stopping any existing process..."
          pkill -f "node agent.js" || echo "No process was running."

          # Start the app with the latest code
          echo "Starting the application..."
          nohup node agent.js > app.log 2>&1 &

          echo "Deployment completed successfully!"
        EOF
