name: Deploy to EC2

# Trigger deployment on push to the main branch
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/ec2_key.pem
        chmod 600 ~/.ssh/ec2_key.pem
        # Add your EC2 instance to known_hosts to avoid authenticity prompt.
        ssh-keyscan -H ec2-54-81-72-20.compute-1.amazonaws.com ~/.ssh/known_hosts

    - name: Deploy to EC2
      run: |
        ssh -i ~/.ssh/ec2_key.pem ec2-user@ec2-user@ec2-54-81-72-20.compute-1.amazonaws.com << 'EOF'
          cd ~/my-node-app
          git pull
          npm install
          pm2 restart my-node-app || pm2 start agent.js --name my-node-app
        EOF
